package com.tonyecoleelection.android.di


class DIConstants {
    object DATA_SHARE_MODULE {
        const val NETWORK_DEVICE_LIST = "NETWORK_DEVICE_LIST"
        const val BLUETOOTH_DEVICE_LIST = "BLUETOOTH_DEVICE_LIST"

        const val SELECTED_LGAS_LIST = "SELECTED_LGAS_LIST"
        const val SELECTED_WARDS_LIST = "SELECTED_WARDS_LIST"

        const val SELECTED_PROFESSIONS_LIST = "SELECTED_PROFESSIONS_LIST"
        const val SELECTED_AGE_GROUPS_LIST = "SELECTED_AGE_GROUPS_LIST"

        const val PROFESSIONS_FILTER_LIST = "PROFESSIONS_FILTER_LIST"
        const val AGE_GROUPS_FILTER_LIST = "AGE_GROUPS_FILTER_LIST"

    }
}